/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\bmw_e36_m3.glb --output .\src\components\BMWE36.jsx --shadows --exportdefault --keepnames --precision 3 --root .\public 
Author: Martin Trafas (https://sketchfab.com/Bexxie)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bmw-e36-m3-762b90efd3dc413cb61c3e3c8097b8ac
Title: BMW E36 M3
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/bmw_e36_m3.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <mesh name="Object_2" castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.HeadLights} />
        <mesh name="Object_3" castShadow receiveShadow geometry={nodes.Object_3.geometry} material={materials.Light} />
        <mesh name="Object_4" castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.LicencePlate} />
        <mesh name="Object_5" castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials.Mirror} />
        <mesh name="Object_6" castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials['Tire.001']} />
        <mesh name="Object_7" castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials['SeconadryColor.001']} />
        <mesh name="Object_8" castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials['Textures.001']} />
        <mesh name="Object_9" castShadow receiveShadow geometry={nodes.Object_9.geometry} material={materials.RearLights} />
        <mesh name="Object_10" castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials.Cover} />
        <mesh name="Object_11" castShadow receiveShadow geometry={nodes.Object_11.geometry} material={materials.CarPaint} />
        <mesh name="Object_12" castShadow receiveShadow geometry={nodes.Object_12.geometry} material={materials.Exhaust} />
        <mesh name="Object_13" castShadow receiveShadow geometry={nodes.Object_13.geometry} material={materials['MainColor.001']} />
        <mesh name="Object_14" castShadow receiveShadow geometry={nodes.Object_14.geometry} material={materials['MainColor.001']} />
        <mesh name="Object_15" castShadow receiveShadow geometry={nodes.Object_15.geometry} material={materials.Plastic} />
        <mesh name="Object_16" castShadow receiveShadow geometry={nodes.Object_16.geometry} material={materials.Plastic} />
        <mesh name="Object_17" castShadow receiveShadow geometry={nodes.Object_17.geometry} material={materials.Windows} />
        <mesh name="Object_18" castShadow receiveShadow geometry={nodes.Object_18.geometry} material={materials.Scene} />
      </group>
    </group>
  )
}

useGLTF.preload('/bmw_e36_m3.glb')
